# _config.yml
title: 天阙教程
description: 使用教程分享
author: wxfyes

# 社交链接
github_username: wxfyes
twitter_username: your_twitter

# 插件
plugins: []

# GitHub Pages 设置
baseurl: ""
url: "https://wxfyes.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge

# 排除文件
exclude:
  - templates/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - start.bat
  - start.sh
  - QUICKSTART.md
  - CHANGELOG.md
  - WRITING-GUIDE.md
