# _config.yml
title: 天阙教程
description: 使用教程分享
author: wxfyes
theme: minima

# 社交链接
github_username: wxfyes
twitter_username: your_twitter

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 分页
paginate: 5
paginate_path: "/page/:num/"
