# _config.yml
title: 天阙教程
description: 使用教程分享
author: wxfyes
theme: minima

# 社交链接
github_username: wxfyes
twitter_username: your_twitter

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 分页
paginate: 5
paginate_path: "/page/:num/"

# GitHub Pages 设置
baseurl: ""
url: "https://wxfyes.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
